import Link from "next/link";
import { CheckCircle2, Database, ExternalLink, Globe2, HardDrive, Save, ShieldCheck } from "lucide-react";
import type { Locale } from "@/i18n/config";
import { requireAdmin } from "@/lib/auth";
import { getSiteSettings } from "@/lib/data";
import { updateSiteSettingsAction } from "@/lib/actions";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const textareaClass="min-h-24 w-full resize-y rounded-xl border border-(--color-line) bg-(--color-ink)/60 px-3 py-3 text-sm text-(--color-ivory) outline-none focus:border-(--color-gold)";
const labelClass="mb-2 block text-xs text-(--color-bone)";

export default async function SettingsPage({params,searchParams}:{params:Promise<{locale:Locale}>;searchParams:Promise<{saved?:string}>}) {
  const {locale}=await params;const {saved}=await searchParams;await requireAdmin(locale);const settings=await getSiteSettings();const ar=locale==="ar";
  const checks=[{label:"Supabase URL",ready:Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL),icon:Database},{label:"Supabase Auth",ready:Boolean(process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY),icon:ShieldCheck},{label:"Storage / Admin API",ready:Boolean(process.env.SUPABASE_SERVICE_ROLE_KEY),icon:HardDrive},{label:"Public site URL",ready:Boolean(process.env.NEXT_PUBLIC_SITE_URL),icon:Globe2}];
  return <div className="mx-auto max-w-6xl"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-[.2em] text-(--color-gold)">{ar?"تحكم كامل بالموقع":"Website control center"}</p><h1 className="mt-2 text-3xl font-semibold">{ar?"المحتوى والتواصل":"Content & contact settings"}</h1><p className="mt-2 text-sm text-(--color-smoke)">{ar?"عدّل النصوص وبيانات التواصل بدون الحاجة لتعديل الكود.":"Edit website copy and contact details without touching code."}</p></div><Link href={`/${locale}`} target="_blank" className="inline-flex items-center gap-2 text-sm text-(--color-gold)">{ar?"فتح الموقع":"Open website"}<ExternalLink size={15}/></Link></div>
    {saved&&<div className="mb-6 flex items-center gap-3 rounded-2xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-sm text-emerald-400"><CheckCircle2 size={18}/>{ar?"تم حفظ التغييرات وتحديث الموقع بنجاح.":"Changes saved and website updated successfully."}</div>}
    <form action={updateSiteSettingsAction.bind(null,locale)} className="space-y-6">
      <Card><CardHeader><CardTitle>{ar?"نصوص الواجهة الرئيسية":"Homepage copy"}</CardTitle><p className="mt-1 text-xs text-(--color-smoke)">{ar?"اترك أي حقل فارغًا لإخفائه من الموقع.":"Leave any field empty to hide it."}</p></CardHeader><CardContent className="grid gap-5 md:grid-cols-2">
        <div><label className={labelClass}>Hero — العربية</label><textarea name="heroDescriptionAr" defaultValue={settings.heroDescriptionAr} className={textareaClass}/></div><div><label className={labelClass}>Hero — English</label><textarea name="heroDescriptionEn" defaultValue={settings.heroDescriptionEn} dir="ltr" className={textareaClass}/></div>
        <div><label className={labelClass}>وصل حديثاً — العربية</label><textarea name="newDescriptionAr" defaultValue={settings.newDescriptionAr} className={textareaClass}/></div><div><label className={labelClass}>New arrivals — English</label><textarea name="newDescriptionEn" defaultValue={settings.newDescriptionEn} dir="ltr" className={textareaClass}/></div>
        <div><label className={labelClass}>الأكثر مبيعاً — العربية</label><textarea name="bestDescriptionAr" defaultValue={settings.bestDescriptionAr} className={textareaClass}/></div><div><label className={labelClass}>Best sellers — English</label><textarea name="bestDescriptionEn" defaultValue={settings.bestDescriptionEn} dir="ltr" className={textareaClass}/></div>
        <div><label className={labelClass}>مكتبة الكتالوجات — العربية</label><textarea name="libraryDescriptionAr" defaultValue={settings.libraryDescriptionAr} className={textareaClass}/></div><div><label className={labelClass}>Catalog library — English</label><textarea name="libraryDescriptionEn" defaultValue={settings.libraryDescriptionEn} dir="ltr" className={textareaClass}/></div>
      </CardContent></Card>
      <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>{ar?"بيانات التواصل":"Contact information"}</CardTitle></CardHeader><CardContent className="space-y-4"><div><label className={labelClass}>{ar?"رقم الهاتف":"Phone"}</label><Input name="phone" defaultValue={settings.phone} dir="ltr" placeholder="+966..."/></div><div><label className={labelClass}>WhatsApp</label><Input name="whatsapp" defaultValue={settings.whatsapp} dir="ltr" placeholder="9665..."/></div><div><label className={labelClass}>{ar?"البريد الإلكتروني":"Email"}</label><Input name="email" type="email" defaultValue={settings.email} dir="ltr" placeholder="sales@consul.com"/></div></CardContent></Card>
      <Card><CardHeader><CardTitle>{ar?"روابط السوشيال ميديا":"Social media links"}</CardTitle></CardHeader><CardContent className="space-y-4"><Input name="instagram" type="url" defaultValue={settings.instagram} dir="ltr" placeholder="Instagram URL"/><Input name="facebook" type="url" defaultValue={settings.facebook} dir="ltr" placeholder="Facebook URL"/><Input name="tiktok" type="url" defaultValue={settings.tiktok} dir="ltr" placeholder="TikTok URL"/><Input name="linkedin" type="url" defaultValue={settings.linkedin} dir="ltr" placeholder="LinkedIn URL"/></CardContent></Card></div>
      <div className="sticky bottom-4 z-20 flex flex-wrap justify-end gap-3 rounded-2xl border border-(--color-line) bg-(--color-ink)/85 p-3 shadow-2xl backdrop-blur-xl"><Button type="submit" name="intent" value="save" variant="outline" className="h-11 px-6"><Save size={16}/>{ar?"حفظ":"Save"}</Button><Button type="submit" name="intent" value="preview" className="h-11 px-6 shadow-xl shadow-(--color-gold)/15"><ExternalLink size={16}/>{ar?"حفظ ومعاينة الموقع":"Save & preview website"}</Button></div>
    </form>
    <Card className="mt-8"><CardHeader><CardTitle>{ar?"حالة الاتصال":"Integration status"}</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{checks.map(({label,ready,icon:Icon})=><div key={label} className="flex items-center justify-between rounded-xl border border-(--color-line) p-4"><div className="flex items-center gap-3"><Icon size={18} className="text-(--color-gold)"/><span className="text-sm">{label}</span></div><Badge className={ready?"border-emerald-400/30 bg-emerald-400/10 text-emerald-400":"border-amber-400/30 bg-amber-400/10 text-amber-400"}>{ready?(ar?"جاهز":"Ready"):(ar?"ناقص":"Missing")}</Badge></div>)}</CardContent></Card>
  </div>;
}
