import Link from "next/link";
import { AlertTriangle, Boxes, PackageCheck, PackageX } from "lucide-react";
import type { Locale } from "@/i18n/config";
import { requirePermission } from "@/lib/auth";
import { getCatalogs, getWarehouses } from "@/lib/data";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default async function InventoryPage({params}:{params:Promise<{locale:Locale}>}){
  const {locale}=await params;await requirePermission(locale,"catalogs.inventory");const [catalogs,warehouses]=await Promise.all([getCatalogs(),getWarehouses()]);const ar=locale==="ar";
  const variants=catalogs.flatMap(c=>c.inventory.map(item=>({catalog:c,item,total:Object.values(item.quantities).reduce((sum,qty)=>sum+qty,0)})));const total=variants.reduce((sum,row)=>sum+row.total,0),out=variants.filter(row=>row.total===0),low=variants.filter(row=>row.total>0&&row.total<=5);
  const stats=[{label:ar?"إجمالي الوحدات":"Total units",value:total,icon:Boxes,color:"text-(--color-gold)"},{label:ar?"الألوان المسجلة":"Tracked variants",value:variants.length,icon:PackageCheck,color:"text-emerald-400"},{label:ar?"مخزون منخفض":"Low stock",value:low.length,icon:AlertTriangle,color:"text-amber-400"},{label:ar?"نفد المخزون":"Out of stock",value:out.length,icon:PackageX,color:"text-red-400"}];
  return <div className="mx-auto max-w-7xl"><div className="mb-6"><p className="text-xs uppercase tracking-[.2em] text-(--color-gold)">{ar?"مراقبة مباشرة":"Live control"}</p><h1 className="mt-2 text-3xl font-semibold">{ar?"مركز المخزون":"Inventory command center"}</h1><p className="mt-2 text-sm text-(--color-smoke)">{ar?"الكميات الفعلية حسب اللون والمستودع، مع تنبيه تلقائي عند الانخفاض أو النفاد.":"Exact stock by color and warehouse, with automatic low and out-of-stock alerts."}</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({label,value,icon:Icon,color})=><Card key={label}><CardContent className="flex items-center justify-between pt-5"><div><p className="text-xs text-(--color-smoke)">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div><Icon className={color} size={24}/></CardContent></Card>)}</div>
  <div className="mt-6 overflow-x-auto rounded-2xl border border-(--color-line) bg-(--color-surface)/70"><table className="w-full min-w-[760px] text-sm"><thead><tr className="text-(--color-smoke)"><th className="p-4 text-start">{ar?"المنتج واللون":"Product & color"}</th>{warehouses.map(w=><th key={w.id} className="p-4 text-center">{ar?w.cityAr:w.cityEn}</th>)}<th className="p-4 text-center">{ar?"الإجمالي":"Total"}</th><th className="p-4 text-center">{ar?"الحالة":"Status"}</th></tr></thead><tbody>{variants.map(({catalog,item,total})=><tr key={`${catalog.id}-${item.color}`} className="border-t border-(--color-line)"><td className="p-4"><Link href={`/${locale}/admin/catalogs/${catalog.id}/edit`} className="font-medium hover:text-(--color-gold)">{ar?catalog.nameAr:catalog.nameEn}</Link><p className="mt-1 text-xs text-(--color-smoke)">{item.color} · {item.sku||catalog.modelCode}</p></td>{warehouses.map(w=><td key={w.id} className="p-4 text-center tabular-nums">{item.quantities[w.id]??0}</td>)}<td className="p-4 text-center font-semibold tabular-nums">{total}</td><td className="p-4 text-center"><Badge className={total===0?"border-red-400/30 bg-red-400/10 text-red-400":total<=5?"border-amber-400/30 bg-amber-400/10 text-amber-400":"border-emerald-400/30 bg-emerald-400/10 text-emerald-400"}>{total===0?(ar?"نفدت الكمية":"Out of stock"):total<=5?(ar?"منخفض":"Low"):(ar?"متوفر":"Available")}</Badge></td></tr>)}{!variants.length&&<tr><td colSpan={warehouses.length+3} className="p-12 text-center text-(--color-smoke)">{ar?"أدخل الكميات والألوان من صفحة تعديل الكتالوج لتظهر هنا.":"Add colors and quantities from catalog editing to populate this center."}</td></tr>}</tbody></table></div></div>;
}
