import { Building2, MapPin, Trash2 } from "lucide-react";
import type { Locale } from "@/i18n/config";
import { requireAdmin } from "@/lib/auth";
import { getCatalogs, getWarehouses } from "@/lib/data";
import { createWarehouseAction, deleteWarehouseAction } from "@/lib/actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export default async function WarehousesAdminPage({params}:{params:Promise<{locale:Locale}>}) {
  const {locale}=await params; await requireAdmin(locale);
  const [warehouses,catalogs]=await Promise.all([getWarehouses(),getCatalogs()]); const ar=locale==="ar";
  return <div className="mx-auto max-w-6xl"><div className="mb-6"><h1 className="text-2xl font-semibold">{ar?"إدارة المستودعات":"Warehouse management"}</h1><p className="mt-1 text-sm text-(--color-smoke)">{ar?"أنشئ فروع العرض واربط الكتالوج الواحد بأكثر من مستودع":"Create sales locations and assign each catalog to multiple warehouses"}</p></div><div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><Card><CardHeader><CardTitle>{ar?"مستودع جديد":"New warehouse"}</CardTitle></CardHeader><CardContent><form action={createWarehouseAction.bind(null,locale)} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><Input name="nameAr" required placeholder="الاسم بالعربية"/><Input name="nameEn" required placeholder="English name" dir="ltr"/><Input name="cityAr" required placeholder="المدينة بالعربية"/><Input name="cityEn" required placeholder="City in English" dir="ltr"/></div><Input name="slug" placeholder="warehouse-slug" dir="ltr"/><textarea name="descriptionAr" placeholder="وصف مختصر بالعربية" className="min-h-20 w-full rounded-lg border border-(--color-line) bg-transparent p-3 text-sm"/><textarea name="descriptionEn" placeholder="Short English description" dir="ltr" className="min-h-20 w-full rounded-lg border border-(--color-line) bg-transparent p-3 text-sm"/><Button className="w-full"><Building2 size={16}/>{ar?"إضافة المستودع":"Add warehouse"}</Button></form></CardContent></Card><Card><CardHeader><CardTitle>{ar?"المستودعات الحالية":"Existing warehouses"}</CardTitle></CardHeader><CardContent className="space-y-3">{warehouses.map(warehouse=>{const count=catalogs.filter(c=>c.warehouseIds.includes(warehouse.id)).length;return <div key={warehouse.id} className="flex items-center justify-between gap-3 rounded-xl border border-(--color-line) p-4"><div className="flex min-w-0 items-center gap-3"><div className="rounded-xl bg-(--color-gold)/10 p-2.5 text-(--color-gold)"><Building2 size={18}/></div><div className="min-w-0"><p className="truncate text-sm text-(--color-ivory)">{ar?warehouse.nameAr:warehouse.nameEn}</p><p className="mt-1 flex items-center gap-1 text-xs text-(--color-smoke)"><MapPin size={12}/>{ar?warehouse.cityAr:warehouse.cityEn} · {count} {ar?"كتالوج":"catalogs"}</p></div></div><form action={deleteWarehouseAction.bind(null,locale,warehouse.id)}><Button variant="ghost" size="icon" aria-label={ar?"حذف":"Delete"} disabled={count>0} title={count>0?(ar?"أزل ارتباط الكتالوجات أولاً":"Unassign catalogs first"):undefined}><Trash2 size={15} className="text-red-400"/></Button></form></div>})}</CardContent></Card></div></div>;
}
