"use client";
import { useMemo, useState, useTransition } from "react";
import Link from "next/link";
import Image from "next/image";
import { DndContext, closestCenter, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, arrayMove, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { ChevronLeft, ChevronRight, GripVertical, Pencil, Search, Trash2 } from "lucide-react";
import type { Catalog, Category, Warehouse } from "@/lib/types";
import type { Locale } from "@/i18n/config";
import { deleteCatalogAction, reorderCatalogsAction } from "@/lib/actions";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import CatalogQrButton from "./CatalogQrButton";

const PAGE_SIZE=8;
function Row({catalog,warehouses,locale,siteUrl,onDelete}:{catalog:Catalog;warehouses:Warehouse[];locale:Locale;siteUrl:string;onDelete:(id:string)=>void}){const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:catalog.id});const [deleting,startDelete]=useTransition();const ar=locale==="ar";function remove(){if(!window.confirm(ar?`هل أنت متأكد من حذف «${catalog.nameAr}»؟ لا يمكن التراجع عن الحذف.`:`Delete “${catalog.nameEn}”? This cannot be undone.`))return;startDelete(async()=>{await deleteCatalogAction(locale,catalog.id);onDelete(catalog.id)})}return <tr ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition}} className={cn("border-t border-(--color-line)",isDragging&&"relative z-10 bg-(--color-surface-2) opacity-80",deleting&&"opacity-50")}>
  <td className="p-3"><button {...attributes} {...listeners} className="cursor-grab text-(--color-smoke)"><GripVertical size={17}/></button></td>
  <td className="p-3"><div className="flex items-center gap-3"><div className="relative size-11 overflow-hidden rounded-lg"><Image src={catalog.coverUrl} alt="" fill className="object-cover"/></div><div><p className="text-sm text-(--color-ivory)">{locale==="ar"?catalog.nameAr:catalog.nameEn}</p><p className="text-xs text-(--color-smoke)">/{catalog.slug}</p></div></div></td>
  <td className="hidden p-3 sm:table-cell"><Badge>{catalog.category}</Badge></td><td className="hidden p-3 lg:table-cell"><div className="flex max-w-xs flex-wrap gap-1">{warehouses.filter(w=>catalog.warehouseIds.includes(w.id)).map(w=><Badge key={w.id} className="border border-(--color-line) bg-transparent text-(--color-bone)">{ar?w.cityAr:w.cityEn}</Badge>)}</div></td><td className="hidden p-3 text-xs text-(--color-bone) md:table-cell">{catalog.productCount}</td>
  <td className="p-3 text-end"><div className="flex justify-end"><CatalogQrButton title={locale==="ar"?catalog.nameAr:catalog.nameEn} url={`${siteUrl}/${locale}/catalog/${catalog.slug}`}/><Link href={`/${locale}/admin/catalogs/${catalog.id}/edit`} aria-label={ar?"تعديل":"Edit"} className={cn(buttonVariants({variant:"ghost",size:"icon"}),"size-8")}><Pencil size={15}/></Link><button type="button" onClick={remove} disabled={deleting} aria-label={ar?"حذف الكتالوج":"Delete catalog"} title={ar?"حذف الكتالوج":"Delete catalog"} className="inline-flex size-8 items-center justify-center rounded-md text-red-400 transition hover:bg-red-500/10 hover:text-red-300 disabled:cursor-wait"><Trash2 size={15}/></button></div></td></tr>}
export default function AdminCatalogList({initialCatalogs,categories,warehouses,locale,siteUrl}:{initialCatalogs:Catalog[];categories:Category[];warehouses:Warehouse[];locale:Locale;siteUrl:string}){
  const [catalogs,setCatalogs]=useState(initialCatalogs);const [query,setQuery]=useState("");const [category,setCategory]=useState("");const [warehouse,setWarehouse]=useState("");const [page,setPage]=useState(1);const [,startTransition]=useTransition();const ar=locale==="ar";
  const filtered=useMemo(()=>catalogs.filter(c=>(!category||c.category===category)&&(!warehouse||c.warehouseIds.includes(warehouse))&&`${c.nameAr} ${c.nameEn} ${c.slug}`.toLowerCase().includes(query.toLowerCase())),[catalogs,query,category,warehouse]);const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));const visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  function dragEnd(e:DragEndEvent){if(!e.over||e.active.id===e.over.id)return;const oldIndex=catalogs.findIndex(c=>c.id===e.active.id);const newIndex=catalogs.findIndex(c=>c.id===e.over?.id);const next=arrayMove(catalogs,oldIndex,newIndex);setCatalogs(next);startTransition(()=>reorderCatalogsAction(locale,next.map(c=>c.id)));}
  return <><div className="mb-4 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute start-3 top-3 text-(--color-smoke)" size={16}/><Input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder={ar?"بحث بالاسم أو الرابط...":"Search name or slug..."} className="ps-9"/></div><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}} className="h-10 rounded-lg border border-(--color-line) bg-(--color-surface) px-3 text-sm"><option value="">{ar?"كل التصنيفات":"All categories"}</option>{categories.map(c=><option key={c.id} value={c.slug}>{ar?c.nameAr:c.nameEn}</option>)}</select><select value={warehouse} onChange={e=>{setWarehouse(e.target.value);setPage(1)}} className="h-10 rounded-lg border border-(--color-line) bg-(--color-surface) px-3 text-sm"><option value="">{ar?"كل المستودعات":"All warehouses"}</option>{warehouses.map(w=><option key={w.id} value={w.id}>{ar?w.nameAr:w.nameEn}</option>)}</select></div>
  <div className="overflow-x-auto rounded-2xl border border-(--color-line) bg-(--color-surface)/70"><DndContext collisionDetection={closestCenter} onDragEnd={dragEnd}><table className="w-full"><thead><tr className="text-start text-xs text-(--color-smoke)"><th className="w-10 p-3"/><th className="p-3 text-start">{ar?"الكتالوج":"Catalog"}</th><th className="hidden p-3 text-start sm:table-cell">{ar?"التصنيف":"Category"}</th><th className="hidden p-3 text-start lg:table-cell">{ar?"المستودعات":"Warehouses"}</th><th className="hidden p-3 text-start md:table-cell">{ar?"المنتجات":"Products"}</th><th/></tr></thead><SortableContext items={visible.map(c=>c.id)} strategy={verticalListSortingStrategy}><tbody>{visible.map(c=><Row key={c.id} catalog={c} warehouses={warehouses} locale={locale} siteUrl={siteUrl} onDelete={id=>setCatalogs(current=>current.filter(c=>c.id!==id))}/>)}</tbody></SortableContext></table></DndContext>{!visible.length&&<p className="p-10 text-center text-sm text-(--color-smoke)">{ar?"لا توجد نتائج":"No results"}</p>}</div>
  <div className="mt-4 flex items-center justify-between text-xs text-(--color-smoke)"><span>{filtered.length} {ar?"كتالوج":"catalogs"}</span><div className="flex items-center gap-2"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronRight size={17}/></button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}><ChevronLeft size={17}/></button></div></div></>}
