import { FolderTree, Trash2 } from "lucide-react";
import type { Locale } from "@/i18n/config";
import { createCategoryAction, deleteCategoryAction } from "@/lib/actions";
import { requirePermission } from "@/lib/auth";
import { getCatalogs, getCategories } from "@/lib/data";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export default async function CategoriesPage({params}:{params:Promise<{locale:Locale}>}){const {locale}=await params;const access=await requirePermission(locale,"categories.view");const canManage=access.permissions.includes("categories.manage");const [categories,catalogs]=await Promise.all([getCategories(),getCatalogs()]);const ar=locale==="ar";return <div className="mx-auto max-w-6xl"><div className="mb-6"><h1 className="text-2xl font-semibold">{ar?"إدارة التصنيفات":"Category management"}</h1><p className="mt-1 text-sm text-(--color-smoke)">{ar?"أنشئ تصنيفات لتنظيم الكتالوجات":"Organize catalogs into categories"}</p></div><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card><CardHeader><CardTitle>{ar?"تصنيف جديد":"New category"}</CardTitle></CardHeader><CardContent><fieldset disabled={!canManage}><form action={createCategoryAction.bind(null,locale)} className="space-y-3"><Input name="nameAr" required placeholder="الاسم بالعربية"/><Input name="nameEn" required placeholder="English name"/><Input name="slug" placeholder="custom-slug" dir="ltr"/><Button className="w-full">{ar?"إضافة":"Add category"}</Button></form></fieldset></CardContent></Card><Card><CardHeader><CardTitle>{ar?"التصنيفات الحالية":"Existing categories"}</CardTitle></CardHeader><CardContent className="space-y-2">{categories.map(category=><div key={category.id} className="flex items-center justify-between rounded-xl border border-(--color-line) p-3"><div className="flex items-center gap-3"><div className="rounded-lg bg-(--color-gold)/10 p-2 text-(--color-gold)"><FolderTree size={16}/></div><div><p className="text-sm">{ar?category.nameAr:category.nameEn}</p><p className="text-xs text-(--color-smoke)">{category.slug} · {catalogs.filter(c=>c.category===category.slug).length}</p></div></div>{canManage&&<form action={deleteCategoryAction.bind(null,locale,category.id)}><Button variant="ghost" size="icon" aria-label={ar?"حذف":"Delete"}><Trash2 size={15} className="text-red-400"/></Button></form>}</div>)}</CardContent></Card></div></div>}
