import { UserPlus, Users } from "lucide-react";
import type { Locale } from "@/i18n/config";
import { createUserAction, toggleUserAction } from "@/lib/actions";
import { requireSuperAdmin } from "@/lib/auth";
import { getSupabaseClient } from "@/lib/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export default async function UsersPage({params}:{params:Promise<{locale:Locale}>}){const {locale}=await params;await requireSuperAdmin(locale);const supabase=getSupabaseClient();const {data:profiles}=supabase?await supabase.from("profiles").select("id,email,full_name,role,active,created_at").order("created_at",{ascending:false}):{data:[]};const ar=locale==="ar";return <div className="mx-auto max-w-6xl"><div className="mb-6"><h1 className="text-2xl font-semibold">{ar?"المستخدمون والصلاحيات":"Users & roles"}</h1><p className="mt-1 text-sm text-(--color-smoke)">{ar?"Admin وEditor وViewer":"Admin, editor, and viewer access"}</p></div>{!supabase&&<div className="mb-5 rounded-xl border border-(--color-gold)/25 bg-(--color-gold)/10 p-4 text-sm text-(--color-gold)">{ar?"أضف SUPABASE_SERVICE_ROLE_KEY لتفعيل إدارة المستخدمين.":"Add SUPABASE_SERVICE_ROLE_KEY to enable user management."}</div>}<div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><UserPlus size={17}/>{ar?"مستخدم جديد":"New user"}</CardTitle></CardHeader><CardContent><form action={createUserAction.bind(null,locale)} className="space-y-3"><Input name="email" type="email" required placeholder="name@company.com"/><Input name="password" type="password" required minLength={8} placeholder={ar?"كلمة مرور مؤقتة":"Temporary password"}/><select name="role" className="h-10 w-full rounded-lg border border-(--color-line) bg-(--color-ink) px-3 text-sm"><option value="viewer">Viewer</option><option value="editor">Editor</option><option value="admin">Admin</option></select><Button disabled={!supabase} className="w-full">{ar?"إنشاء المستخدم":"Create user"}</Button></form></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Users size={17}/>{ar?"الفريق":"Team"}</CardTitle></CardHeader><CardContent className="space-y-2">{profiles?.map(p=><div key={p.id} className="flex items-center justify-between rounded-xl border border-(--color-line) p-3"><div><p className="text-sm">{p.full_name||p.email}</p><p className="text-xs text-(--color-smoke)">{p.email}</p></div><div className="flex items-center gap-2"><Badge>{p.role}</Badge><form action={toggleUserAction.bind(null,locale,p.id,!p.active)}><Button size="sm" variant={p.active?"outline":"default"}>{p.active?(ar?"تعطيل":"Disable"):(ar?"تفعيل":"Enable")}</Button></form></div></div>)}{!profiles?.length&&<p className="py-8 text-center text-sm text-(--color-smoke)">{ar?"لا يوجد مستخدمون بعد":"No users yet"}</p>}</CardContent></Card></div></div>}
