import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, BookOpen, FolderTree, ImageIcon, Plus, QrCode, Sparkles } from "lucide-react";
import type { Locale } from "@/i18n/config";
import { requirePermission } from "@/lib/auth";
import { getCatalogs, getCategories } from "@/lib/data";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export default async function AdminDashboard({params}:{params:Promise<{locale:Locale}>}) {
  const {locale}=await params;await requirePermission(locale,"dashboard.view");const [catalogs,categories]=await Promise.all([getCatalogs(),getCategories()]);const ar=locale==="ar";const totalImages=catalogs.reduce((n,c)=>n+c.images.length,0);const totalProducts=catalogs.reduce((n,c)=>n+c.productCount,0);const stats=[{label:ar?"الكتالوجات النشطة":"Active catalogs",value:catalogs.length,detail:ar?"جاهزة للمشاركة":"Ready to share",icon:BookOpen},{label:ar?"إجمالي المنتجات":"Products showcased",value:totalProducts,detail:ar?"ضمن كل المجموعات":"Across collections",icon:Sparkles},{label:ar?"صفحات العرض":"Catalog pages",value:totalImages,detail:ar?"صور عالية الجودة":"High-quality visuals",icon:ImageIcon},{label:ar?"التصنيفات":"Categories",value:categories.length,detail:ar?"تنظيم واضح":"Organized library",icon:FolderTree}];const max=Math.max(...catalogs.map(c=>c.productCount),1);const quickActions=[{icon:BookOpen,label:ar?"إدارة الكتالوجات":"Manage catalogs",href:`/${locale}/admin/catalogs`},{icon:FolderTree,label:ar?"تنظيم التصنيفات":"Organize categories",href:`/${locale}/admin/categories`},{icon:QrCode,label:ar?"إنشاء روابط QR":"Generate QR links",href:`/${locale}/admin/catalogs`}];
  return <div className="mx-auto max-w-7xl">
    <section className="relative mb-7 overflow-hidden rounded-[2rem] border border-(--color-gold)/15 bg-(--color-surface)/70 p-6 shadow-[0_30px_100px_rgba(0,0,0,.15)] backdrop-blur-2xl md:p-8"><div className="absolute end-0 top-0 size-80 rounded-full bg-(--color-gold)/10 blur-[100px]"/><div className="relative flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><Badge className="mb-4">{ar?"مركز قيادة المبيعات":"Sales content command center"}</Badge><h1 className="max-w-2xl text-3xl font-semibold leading-tight md:text-5xl">{ar?"كل ما يحتاجه فريقك، جاهز أمام العميل.":"Everything your team needs, ready for the client."}</h1><p className="mt-4 max-w-xl text-sm leading-7 text-(--color-smoke)">{ar?"نظّم المجموعات، حدّث صفحات العرض، وأنشئ روابط المشاركة من مكان واحد.":"Organize collections, update presentations, and generate client-ready sharing links from one place."}</p></div><div className="flex flex-wrap gap-3"><Link href={`/${locale}/admin/catalogs/new`} className={buttonVariants()}><Plus size={16}/>{ar?"كتالوج جديد":"New catalog"}</Link><Link href={`/${locale}/admin/catalogs`} className={cn(buttonVariants({variant:"outline"}))}>{ar?"فتح المكتبة":"Open library"}<ArrowUpRight size={15}/></Link></div></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({label,value,detail,icon:Icon},index)=><Card key={label} className="group overflow-hidden"><CardContent className="relative flex items-start justify-between pt-5"><span className="absolute inset-x-0 bottom-0 h-0.5 origin-start scale-x-0 bg-(--color-gold) transition group-hover:scale-x-100"/><div><p className="text-xs text-(--color-smoke)">{label}</p><p className="mt-3 text-4xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-[11px] text-(--color-smoke)">{detail}</p></div><div className="rounded-2xl border border-(--color-gold)/15 bg-(--color-gold)/8 p-3 text-(--color-gold)"><Icon size={19}/></div><span className="absolute end-4 bottom-3 text-[10px] text-(--color-line)">0{index+1}</span></CardContent></Card>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>{ar?"أداء مكتبة العرض":"Presentation library"}</CardTitle><p className="mt-1 text-xs text-(--color-smoke)">{ar?"حجم المنتجات داخل كل كتالوج":"Products per catalog"}</p></div><Link href={`/${locale}/admin/catalogs`} className="text-xs text-(--color-gold)">{ar?"عرض الكل":"View all"}</Link></CardHeader><CardContent className="space-y-5">{catalogs.slice(0,6).map(c=><div key={c.id}><div className="mb-2 flex justify-between text-xs"><span>{ar?c.nameAr:c.nameEn}</span><span className="text-(--color-smoke)">{c.productCount} {ar?"منتج":"products"}</span></div><div className="h-2 overflow-hidden rounded-full bg-(--color-line)"><div className="h-full rounded-full bg-gradient-to-r from-(--color-gold-deep) via-(--color-gold) to-(--color-gold-bright)" style={{width:`${Math.max(5,c.productCount/max*100)}%`}}/></div></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>{ar?"أحدث المجموعات":"Recent collections"}</CardTitle></CardHeader><CardContent className="space-y-3">{[...catalogs].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,4).map(c=><Link key={c.id} href={`/${locale}/admin/catalogs/${c.id}/edit`} className="group flex items-center gap-3 rounded-xl border border-transparent p-2 transition hover:border-(--color-line) hover:bg-(--color-surface-2)"><div className="relative size-12 overflow-hidden rounded-xl"><Image src={c.coverUrl} alt="" fill sizes="48px" className="object-cover"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm">{ar?c.nameAr:c.nameEn}</p><p className="mt-1 text-[10px] text-(--color-smoke)">{c.category} · {c.images.length} {ar?"صفحة":"pages"}</p></div><ArrowUpRight size={14} className="text-(--color-smoke) transition group-hover:text-(--color-gold)"/></Link>)}</CardContent></Card></div>
    <div className="mt-6 grid gap-4 md:grid-cols-3">{quickActions.map(({icon:Icon,label,href})=><Link key={String(label)} href={String(href)} className="group flex items-center justify-between rounded-2xl border border-(--color-line) bg-(--color-surface)/50 p-5 transition hover:-translate-y-1 hover:border-(--color-gold)/30"><div className="flex items-center gap-3"><Icon className="text-(--color-gold)" size={19}/><span className="text-sm">{label}</span></div><ArrowUpRight size={16}/></Link>)}</div>
  </div>;
}
