import Image from "next/image";
import Link from "next/link";
import { ExternalLink, MessageCircle, Presentation, Share2 } from "lucide-react";
import type { Locale } from "@/i18n/config";
import { requirePermission } from "@/lib/auth";
import { getCatalogs } from "@/lib/data";
import CatalogQrButton from "@/components/admin/CatalogQrButton";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export default async function ShareCenter({params}:{params:Promise<{locale:Locale}>}){const {locale}=await params;await requirePermission(locale,"catalogs.view");const catalogs=await getCatalogs();const ar=locale==="ar";const siteUrl=process.env.NEXT_PUBLIC_SITE_URL??"http://localhost:3000";return <div className="mx-auto max-w-7xl"><section className="mb-7 overflow-hidden rounded-[2rem] border border-(--color-gold)/20 bg-[radial-gradient(circle_at_top_left,rgba(201,162,39,.2),transparent_40%)] p-7"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs uppercase tracking-[.2em] text-(--color-gold)">{ar?"جاهز أمام العميل":"Client-ready"}</p><h1 className="mt-2 text-3xl font-semibold">{ar?"مركز مشاركة المندوب":"Sales sharing center"}</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-(--color-smoke)">{ar?"افتح الكتالوج بوضع العرض أو أرسله مباشرة عبر واتساب أو QR خلال ثوانٍ.":"Open any catalog in presentation mode or share it instantly through WhatsApp or QR."}</p></div><Presentation size={48} className="text-(--color-gold)"/></div></section><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{catalogs.map(c=>{const url=`${siteUrl}/${locale}/catalog/${c.slug}`;const title=ar?c.nameAr:c.nameEn;const message=encodeURIComponent(`${title}\n${url}`);return <Card key={c.id} className="overflow-hidden"><div className="relative aspect-[16/9] bg-white"><Image src={c.coverUrl} alt={title} fill sizes="(max-width:768px) 100vw, 33vw" className="object-contain"/></div><CardHeader><CardTitle className="truncate text-base">{title}</CardTitle><p className="text-xs text-(--color-smoke)">{c.modelCode} · {c.images.length} {ar?"صورة":"images"}</p></CardHeader><CardContent className="flex flex-wrap gap-2"><Link href={`/${locale}/catalog/${c.slug}`} target="_blank" className={cn(buttonVariants({size:"sm"}),"flex-1")}><ExternalLink size={14}/>{ar?"وضع العرض":"Present"}</Link><Link href={`https://wa.me/?text=${message}`} target="_blank" className={cn(buttonVariants({variant:"outline",size:"sm"}),"flex-1")}><MessageCircle size={14}/>WhatsApp</Link><CatalogQrButton title={title} url={url}/></CardContent></Card>})}</div>{!catalogs.length&&<div className="py-16 text-center text-(--color-smoke)"><Share2 className="mx-auto"/><p className="mt-3">{ar?"لا توجد كتالوجات للمشاركة بعد.":"No catalogs available to share."}</p></div>}</div>}
